name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'
        include-prerelease: True
    - name: Build AngularAzureADMultipleApis
      run: dotnet build ./AngularAzureADMultipleApis/ApiWithMutlipleApis.sln
    - name: Build BlazorWithApis
      run: dotnet build ./BlazorWithApis/BlazorApis.sln
    - name: Build ConfidentialClientCredentialsCertificate
      run: dotnet build ./ConfidentialClientCredentialsCertificate/ConfidentialClientCredentialsCertificate.sln
    - name: Build DecryptionCertificates
      run: dotnet build ./DecryptionCertificates/DecryptionCertificates.sln
    - name: Build DeviceFlowWeb
      run: dotnet build ./DeviceFlowWeb/DeviceFlowWeb.sln
    - name: Build DownstreamApis
      run: dotnet build ./DownstreamApis/DownstreamApis.sln
    - name: Build TokenManagement
      run: dotnet build ./TokenManagement/TokenManagement.sln

